Repository princeton-nlp/SWE-agent, pull requests merged in 2024-04, with the labels that each got.

#6 Update README.md - Fix broken links
  README.md
Labels: documentation

#31 fix: allow token from keys.cfg to get passed to ghapi
  sweagent/environment/swe_env.py
  sweagent/environment/utils.py
Labels: bug

#32 Fix unbound variable in error handling
  sweagent/environment/swe_env.py
Labels: bug

#33 More helpful error message if docker is not running
  sweagent/environment/swe_env.py
Labels: enhancement

#12 chore: remove gnureadline dependency
  environment.yml
  setup.py
Labels: code quality

#49 Handle with missing prompt_eval_count in Ollama
  sweagent/agent/models.py
Labels: bug

#9 feat(models): natively support claude haiku
  sweagent/agent/models.py
Labels: feature

#35 Feat: Open PR to repo
  run.py
  sweagent/agent/agents.py
  sweagent/environment/swe_env.py
  sweagent/environment/utils.py
Labels: feature

#58 Fix: Allow run_replay with github URLs as data_path
  run_replay.py
Labels: bug

#16 feat: add support for azure openai
  README.md
  sweagent/agent/models.py
Labels: feature

#65 Fix searching for flag-like strings, e.g., search_file "--flag"
  config/commands/search.sh
Labels: bug

#81 Containerize application
  Dockerfile
Labels: enhancement

#90 Add run via docker instructions to readme
  README.md
Labels: documentation

#56 Small refactor: Add quicksart section
  README.md
Labels: documentation

#79 fix: bad newline getting sent on windows
  sweagent/environment/swe_env.py
Labels: bug, os:windows

#125 Improve ease of debugging
  run.py
  run_replay.py
Labels: code quality

#154 Increase coverage of swe-env tests
  run.py
  sweagent/environment/swe_env.py
  tests/test_env.py
Labels: CI

#153 Allow to supply installation commands when running on gh issues
  sweagent/environment/swe_env.py
  tests/test_env.py
Labels: feature

#72 refactor: Simple refactoring for clean code
  run.py
  sweagent/agent/models.py
Labels: code quality

#176 Fix warnings about simple_parsing import paths
  run.py
  sweagent/agent/agents.py
  sweagent/agent/commands.py
  sweagent/agent/models.py
  sweagent/environment/swe_env.py
Labels: code quality

#177 Fix signature of ParseCommandDetailed
  sweagent/agent/commands.py
Labels: 🐛 bug

#174 Use ruff and enable some more checks
  .pre-commit-config.yaml
  evaluation/evaluation.py
  inspector/server.py
  pyproject.toml
  run_replay.py
  sweagent/__init__.py
  sweagent/agent/agents.py
  sweagent/agent/models.py
  sweagent/environment/swe_env.py
  sweagent/environment/utils.py
  tests/test_models.py
Labels: code quality

#184 Test creation of persistent container
  tests/test_env.py
Labels: 🧪 CI

#187 Typing fixes & improvements
  sweagent/agent/agents.py
  sweagent/agent/models.py
  sweagent/environment/swe_env.py
Labels: 🧪 CI

#193 Allow to run on local repos
  run.py
  run_replay.py
  sweagent/environment/swe_env.py
  sweagent/environment/utils.py
  tests/conftest.py
  tests/test_data/data_sources/debug_20240322.json
  tests/test_data/data_sources/human_eval.json
  tests/test_data/data_sources/swe-bench-dev-easy.json
  tests/test_data/data_sources/swe-bench-dev-easy_first_only.json
  tests/test_data/data_sources/swe-bench-lite-test.json
  tests/test_data/trajectories/gpt4__swe-agent-test-repo__default_from_url__t-0.00__p-0.95__c-3.00__install-1/6e44b9__sweagenttestrepo-1c2844.traj
  tests/test_data/trajectories/gpt4__swe-agent-test-repo__default_from_url__t-0.00__p-0.95__c-3.00__install-1/args.yaml
  tests/test_data/trajectories/gpt4__swe-agent-test-repo__default_from_url__t-0.00__p-0.95__c-3.00__install-1/solution_missing_colon.py
  tests/test_data/trajectories/gpt4__swe-bench-dev-easy_first_only__default__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl
  tests/test_data/trajectories/gpt4__swe-bench-dev-easy_first_only__default__t-0.00__p-0.95__c-3.00__install-1/args.yaml
  tests/test_data/trajectories/gpt4__swe-bench-dev-easy_first_only__default__t-0.00__p-0.95__c-3.00__install-1/patches/pydicom__pydicom-1458.patch
  tests/test_data/trajectories/gpt4__swe-bench-dev-easy_first_only__default__t-0.00__p-0.95__c-3.00__install-1/pydicom__pydicom-1458.traj
  tests/test_env.py
  tests/test_replay.py
  tests/test_run.py
  tests/test_utils.py
Labels: ➕ feature

#249 fix: TARGETARCH not set on some OS/docker setups
  setup.sh
Labels: 🐛 bug

#252 Add GPT4-turbo model
  sweagent/agent/models.py
Labels: ✨ enhancement

#207 feat: Amazon Bedrock support (Claude models)
  Dockerfile
  docker/requirements.txt
  environment.yml
  setup.py
  sweagent/agent/README.md
  sweagent/agent/models.py
Labels: ➕ feature

#236 Fix Together model validation error
  environment.yml
  sweagent/agent/models.py
  tests/test_models.py
Labels: 🐛 bug
