Repository princeton-nlp/SWE-agent, pull requests merged in 2024-05, with the labels that each got.

#350 Web: Refactor state into one runConfig with use-immer
  sweagent/api/server.py
  sweagent/api/utils.py
  sweagent/frontend/package-lock.json
  sweagent/frontend/package.json
  sweagent/frontend/src/Run.js
  sweagent/frontend/src/components/controls/LRunControl.js
Labels: 🔧 refactor

#358 Web: Allow to specify commit hash
  sweagent/api/server.py
  sweagent/environment/utils.py
  sweagent/frontend/src/Run.js
  sweagent/frontend/src/components/controls/LRunControl.js
Labels: frontend

#360 CI: Use uv pip install
  .github/workflows/pytest.yaml
Labels: 🧪 CI

#332 Fix typo in inspector server.py
  inspector/server.py
Labels: 🐛 bug

#351 Add default environment_setup config
  config/environment_setup/py310_default.yaml
Labels: 📖 documentation

#274 deprecate action from get_submission
  sweagent/environment/swe_env.py
Labels: 🔧 refactor

#317 Speed up evaluation by caching task environments as docker images
  run.py
  sweagent/environment/swe_env.py
  sweagent/environment/utils.py
Labels: ✨ enhancement
